language: php
php:
  - 5.6

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - mysql -e 'create database overwatch;'
    - mysql -e 'create database overwatch_test;'
    - wget -P bin/ http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
    - composer install --prefer-source
    - php app/console doctrine:schema:create --env=test
    - java -jar bin/selenium-server-standalone-2.37.0.jar &
script: phpunit -c app/

branches:
  only:
    - master
