language: php
php:
  - 5.6

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - mysql -e 'create database overwatch;'
    - mysql -e 'create database overwatch_test;'
    - composer install --prefer-source
    - php app/console doctrine:schema:create --env=test
script: phpunit -c app/

branches:
  only:
    - master
