overwatch_result:
    resource: "@OverwatchResultBundle/Controller/"
    type:     annotation
    prefix:   /

overwatch_test:
    resource: "@OverwatchTestBundle/Controller/"
    type:     annotation
    prefix:   /