overwatch_user:
    resource: "@OverwatchUserBundle/Controller/"
    type:     annotation
    prefix:   /

overwatch_result:
    resource: "@OverwatchResultBundle/Controller/"
    type:     annotation
    prefix:   /

overwatch_test:
    resource: "@OverwatchTestBundle/Controller/"
    type:     annotation
    prefix:   /
    
overwatch_expectation:
    resource: "@OverwatchExpectationBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# FOSUserBundle tries to redirect to a "fos_user_profile_show" route after
# changing password. Here we override it to the app index.
fos_user_profile_show:
    path: /
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc